name: Lint and Jenkins Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Run checkstyle
        run: ./gradlew checkstyleMain